### ISSUE TITLE
Please update PocketMine-MP_1.5dev-1258

### ISSUE THREAD

**Issue by atTheDisco** [luca28pet/BanClient#2]
When using the current version gives server crash.

Please update banclient on the current build 1258

**Comment by atTheDisco** [comment]
Help plzz

**Comment by luca28pet** [comment]
The plugin works fine for me.
Can you send the crash report?

**Comment by atTheDisco** [comment]
Server crash it gives pocketmine build 1258. This crash is happening when you try to enter the game banned player.

Consol log: http://pastebin.com/01ADbcy6
Crash report: http://pastebin.com/ad6hj941

**Comment by Pub4Game** [comment]
@luca28pet When you fix the bug?

**Comment by kmdh1976** [comment]
I'm having the exact same crash as AtTheDisco when banned player try's to enter the game the server crashes I'm running build 1258
hopefully you can fix soon this plugin is a great concept!

**Comment by luca28pet** [comment]
This crash seems to be caused by EssentialsPE: https://github.com/LegendOfMCPE/EssentialsPE/issues/153

**Comment by Pub4Game** [comment]
@luca28pet http://pastebin.com/YKcu7d4Y

The crash occurs after the banned player tries to connect the server

**Comment by atTheDisco** [comment]
@luca28pet I don't use EssentialsPE 

The crash occurs after the banned player tries to connect the server
